### ISSUE TITLE
Crash when trying to navigate after app was restarted (manually or via process death)

### ISSUE THREAD

**Issue by nicoqueijo** [nicoqueijo/Android-Currency-Converter#15]
Example error: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nicoqueijo.android.currencyconverter, PID: 16732
    java.lang.IllegalArgumentException: navigation destination com.nicoqueijo.android.currencyconverter:id/action_watchlistFragment_to_selectorFragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:914)
        at com.nicoqueijo.android.currencyconverter.kotlin.view.WatchlistFragment$initFloatingActionButton$$inlined$apply$lambda$1.onClick(WatchlistFragment.kt:141)
        at android.view.View.performClick(View.java:7869)
        at android.view.View.performClickInternal(View.java:7838)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29362)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by nicoqueijo** [comment]
Fixed in commit 412142215283e45b9d832beb5e07f01c6c29cc7a
